### ISSUE TITLE
反馈项目存在Bug

### ISSUE THREAD

**Issue by OYCodeSite** [zykjofficial-actions/screen_shot#2]
博客使用有拍云CDN加速存在问题，无法验证SSL证书。
**报错信息**：requests.exceptions.SSLError: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: /link/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')))
**解决方式**：只需修改 screen_shot.py ； html = requests.get(url=link,verify=False).content 中添加verify=False 直接取消ssl证书验证即可。

**Comment by zykjofficial** [comment]
好的、谢谢反馈
